//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 11:02:53 AM AST 
//


package com.dovico.importexporttool.xsd.settings;

import jakarta.xml.bind.annotation.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dovico.importexporttool.xsd.settings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dovico.importexporttool.xsd.settings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link State.CurrentMappings }
     * 
     */
    public State.CurrentMappings createStateCurrentMappings() {
        return new State.CurrentMappings();
    }

    /**
     * Create an instance of {@link State.CurrentMappings.FieldItemMap }
     * 
     */
    public State.CurrentMappings.FieldItemMap createStateCurrentMappingsFieldItemMap() {
        return new State.CurrentMappings.FieldItemMap();
    }

    /**
     * Create an instance of {@link State.CurrentMappings.FieldItemMap.Destination }
     * 
     */
    public State.CurrentMappings.FieldItemMap.Destination createStateCurrentMappingsFieldItemMapDestination() {
        return new State.CurrentMappings.FieldItemMap.Destination();
    }

    /**
     * Create an instance of {@link State.CurrentMappings.FieldItemMap.Source }
     * 
     */
    public State.CurrentMappings.FieldItemMap.Source createStateCurrentMappingsFieldItemMapSource() {
        return new State.CurrentMappings.FieldItemMap.Source();
    }

    /**
     * Create an instance of {@link State.ColumnsInFile }
     * 
     */
    public State.ColumnsInFile createStateColumnsInFile() {
        return new State.ColumnsInFile();
    }

    /**
     * Create an instance of {@link State.ColumnsInFile.FieldItem }
     * 
     */
    public State.ColumnsInFile.FieldItem createStateColumnsInFileFieldItem() {
        return new State.ColumnsInFile.FieldItem();
    }

    /**
     * Create an instance of {@link State.ColumnsInFile.FieldItem.CustomField }
     * 
     */
    public State.ColumnsInFile.FieldItem.CustomField createStateColumnsInFileFieldItemCustomField() {
        return new State.ColumnsInFile.FieldItem.CustomField();
    }

    /**
     * Create an instance of {@link State.ColumnsInFile.FieldItem.CustomField.Values }
     * 
     */
    public State.ColumnsInFile.FieldItem.CustomField.Values createStateColumnsInFileFieldItemCustomFieldValues() {
        return new State.ColumnsInFile.FieldItem.CustomField.Values();
    }

    /**
     * Create an instance of {@link State.CurrentMappings.FieldItemMap.Destination.FieldItem }
     * 
     */
    public State.CurrentMappings.FieldItemMap.Destination.FieldItem createStateCurrentMappingsFieldItemMapDestinationFieldItem() {
        return new State.CurrentMappings.FieldItemMap.Destination.FieldItem();
    }

    /**
     * Create an instance of {@link State.CurrentMappings.FieldItemMap.Source.FieldItem }
     * 
     */
    public State.CurrentMappings.FieldItemMap.Source.FieldItem createStateCurrentMappingsFieldItemMapSourceFieldItem() {
        return new State.CurrentMappings.FieldItemMap.Source.FieldItem();
    }

    /**
     * Create an instance of {@link State.ColumnsInFile.FieldItem.CustomField.Values.Value }
     * 
     */
    public State.ColumnsInFile.FieldItem.CustomField.Values.Value createStateColumnsInFileFieldItemCustomFieldValuesValue() {
        return new State.ColumnsInFile.FieldItem.CustomField.Values.Value();
    }

}
