//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 11:02:53 AM AST 
//


package com.dovico.importexporttool.xsd.settings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ColumnsInFile">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FieldItem" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CustomField" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="TemplateID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Hide" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Values">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Value" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CurrentMappings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FieldItemMap" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Source">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FieldItem">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Destination">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FieldItem">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "filePath",
    "destination",
    "columnsInFile",
    "currentMappings"
})
@XmlRootElement(name = "State")
public class State {

    @XmlElement(name = "FilePath", required = true)
    protected String filePath;
    @XmlElement(name = "Destination", required = true)
    protected String destination;
    @XmlElement(name = "ColumnsInFile", required = true)
    protected State.ColumnsInFile columnsInFile;
    @XmlElement(name = "CurrentMappings", required = true)
    protected State.CurrentMappings currentMappings;

    /**
     * Gets the value of the filePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * Sets the value of the filePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilePath(String value) {
        this.filePath = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the columnsInFile property.
     * 
     * @return
     *     possible object is
     *     {@link State.ColumnsInFile }
     *     
     */
    public State.ColumnsInFile getColumnsInFile() {
        return columnsInFile;
    }

    /**
     * Sets the value of the columnsInFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link State.ColumnsInFile }
     *     
     */
    public void setColumnsInFile(State.ColumnsInFile value) {
        this.columnsInFile = value;
    }

    /**
     * Gets the value of the currentMappings property.
     * 
     * @return
     *     possible object is
     *     {@link State.CurrentMappings }
     *     
     */
    public State.CurrentMappings getCurrentMappings() {
        return currentMappings;
    }

    /**
     * Sets the value of the currentMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link State.CurrentMappings }
     *     
     */
    public void setCurrentMappings(State.CurrentMappings value) {
        this.currentMappings = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FieldItem" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CustomField" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TemplateID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Hide" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Values">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Value" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldItem"
    })
    public static class ColumnsInFile {

        @XmlElement(name = "FieldItem")
        protected List<State.ColumnsInFile.FieldItem> fieldItem;

        /**
         * Gets the value of the fieldItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fieldItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFieldItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link State.ColumnsInFile.FieldItem }
         * 
         * 
         */
        public List<State.ColumnsInFile.FieldItem> getFieldItem() {
            if (fieldItem == null) {
                fieldItem = new ArrayList<State.ColumnsInFile.FieldItem>();
            }
            return this.fieldItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CustomField" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TemplateID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Hide" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Values">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Value" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "order",
            "caption",
            "elementName",
            "fieldType",
            "isRoot",
            "parentElementName",
            "rootElementName",
            "customField"
        })
        public static class FieldItem {

            @XmlElement(name = "Order")
            protected byte order;
            @XmlElement(name = "Caption", required = true)
            protected String caption;
            @XmlElement(name = "ElementName", required = true)
            protected String elementName;
            @XmlElement(name = "FieldType", required = true)
            protected String fieldType;
            @XmlElement(name = "IsRoot", required = true)
            protected String isRoot;
            @XmlElement(name = "ParentElementName", required = true)
            protected String parentElementName;
            @XmlElement(name = "RootElementName", required = true)
            protected String rootElementName;
            @XmlElement(name = "CustomField")
            protected State.ColumnsInFile.FieldItem.CustomField customField;

            /**
             * Gets the value of the order property.
             * 
             */
            public byte getOrder() {
                return order;
            }

            /**
             * Sets the value of the order property.
             * 
             */
            public void setOrder(byte value) {
                this.order = value;
            }

            /**
             * Gets the value of the caption property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCaption() {
                return caption;
            }

            /**
             * Sets the value of the caption property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCaption(String value) {
                this.caption = value;
            }

            /**
             * Gets the value of the elementName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getElementName() {
                return elementName;
            }

            /**
             * Sets the value of the elementName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setElementName(String value) {
                this.elementName = value;
            }

            /**
             * Gets the value of the fieldType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFieldType() {
                return fieldType;
            }

            /**
             * Sets the value of the fieldType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFieldType(String value) {
                this.fieldType = value;
            }

            /**
             * Gets the value of the isRoot property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsRoot() {
                return isRoot;
            }

            /**
             * Sets the value of the isRoot property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsRoot(String value) {
                this.isRoot = value;
            }

            /**
             * Gets the value of the parentElementName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParentElementName() {
                return parentElementName;
            }

            /**
             * Sets the value of the parentElementName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParentElementName(String value) {
                this.parentElementName = value;
            }

            /**
             * Gets the value of the rootElementName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRootElementName() {
                return rootElementName;
            }

            /**
             * Sets the value of the rootElementName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRootElementName(String value) {
                this.rootElementName = value;
            }

            /**
             * Gets the value of the customField property.
             * 
             * @return
             *     possible object is
             *     {@link State.ColumnsInFile.FieldItem.CustomField }
             *     
             */
            public State.ColumnsInFile.FieldItem.CustomField getCustomField() {
                return customField;
            }

            /**
             * Sets the value of the customField property.
             * 
             * @param value
             *     allowed object is
             *     {@link State.ColumnsInFile.FieldItem.CustomField }
             *     
             */
            public void setCustomField(State.ColumnsInFile.FieldItem.CustomField value) {
                this.customField = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TemplateID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Hide" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Values">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Value" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "templateID",
                "required",
                "hide",
                "values"
            })
            public static class CustomField {

                @XmlElement(name = "TemplateID")
                protected byte templateID;
                @XmlElement(name = "Required", required = true)
                protected String required;
                @XmlElement(name = "Hide", required = true)
                protected String hide;
                @XmlElement(name = "Values", required = true)
                protected State.ColumnsInFile.FieldItem.CustomField.Values values;

                /**
                 * Gets the value of the templateID property.
                 * 
                 */
                public byte getTemplateID() {
                    return templateID;
                }

                /**
                 * Sets the value of the templateID property.
                 * 
                 */
                public void setTemplateID(byte value) {
                    this.templateID = value;
                }

                /**
                 * Gets the value of the required property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequired() {
                    return required;
                }

                /**
                 * Sets the value of the required property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequired(String value) {
                    this.required = value;
                }

                /**
                 * Gets the value of the hide property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHide() {
                    return hide;
                }

                /**
                 * Sets the value of the hide property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHide(String value) {
                    this.hide = value;
                }

                /**
                 * Gets the value of the values property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link State.ColumnsInFile.FieldItem.CustomField.Values }
                 *     
                 */
                public State.ColumnsInFile.FieldItem.CustomField.Values getValues() {
                    return values;
                }

                /**
                 * Sets the value of the values property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link State.ColumnsInFile.FieldItem.CustomField.Values }
                 *     
                 */
                public void setValues(State.ColumnsInFile.FieldItem.CustomField.Values value) {
                    this.values = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Value" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Values {

                    @XmlElement(name = "Value")
                    protected List<State.ColumnsInFile.FieldItem.CustomField.Values.Value> value;

                    /**
                     * Gets the value of the value property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the value property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getValue().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link State.ColumnsInFile.FieldItem.CustomField.Values.Value }
                     * 
                     * 
                     */
                    public List<State.ColumnsInFile.FieldItem.CustomField.Values.Value> getValue() {
                        if (value == null) {
                            value = new ArrayList<State.ColumnsInFile.FieldItem.CustomField.Values.Value>();
                        }
                        return this.value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="Default" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "_default",
                        "value"
                    })
                    public static class Value {

                        @XmlElement(name = "Default", required = true)
                        protected String _default;
                        @XmlElement(name = "Value", required = true)
                        protected String value;

                        /**
                         * Gets the value of the default property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getDefault() {
                            return _default;
                        }

                        /**
                         * Sets the value of the default property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setDefault(String value) {
                            this._default = value;
                        }

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FieldItemMap" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Source">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="FieldItem">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Destination">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="FieldItem">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldItemMap"
    })
    public static class CurrentMappings {

        @XmlElement(name = "FieldItemMap")
        protected List<State.CurrentMappings.FieldItemMap> fieldItemMap;

        /**
         * Gets the value of the fieldItemMap property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fieldItemMap property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFieldItemMap().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link State.CurrentMappings.FieldItemMap }
         * 
         * 
         */
        public List<State.CurrentMappings.FieldItemMap> getFieldItemMap() {
            if (fieldItemMap == null) {
                fieldItemMap = new ArrayList<State.CurrentMappings.FieldItemMap>();
            }
            return this.fieldItemMap;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Source">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="FieldItem">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Destination">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="FieldItem">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "source",
            "destination"
        })
        public static class FieldItemMap {

            @XmlElement(name = "Source", required = true)
            protected State.CurrentMappings.FieldItemMap.Source source;
            @XmlElement(name = "Destination", required = true)
            protected State.CurrentMappings.FieldItemMap.Destination destination;

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link State.CurrentMappings.FieldItemMap.Source }
             *     
             */
            public State.CurrentMappings.FieldItemMap.Source getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link State.CurrentMappings.FieldItemMap.Source }
             *     
             */
            public void setSource(State.CurrentMappings.FieldItemMap.Source value) {
                this.source = value;
            }

            /**
             * Gets the value of the destination property.
             * 
             * @return
             *     possible object is
             *     {@link State.CurrentMappings.FieldItemMap.Destination }
             *     
             */
            public State.CurrentMappings.FieldItemMap.Destination getDestination() {
                return destination;
            }

            /**
             * Sets the value of the destination property.
             * 
             * @param value
             *     allowed object is
             *     {@link State.CurrentMappings.FieldItemMap.Destination }
             *     
             */
            public void setDestination(State.CurrentMappings.FieldItemMap.Destination value) {
                this.destination = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="FieldItem">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fieldItem"
            })
            public static class Destination {

                @XmlElement(name = "FieldItem", required = true)
                protected State.CurrentMappings.FieldItemMap.Destination.FieldItem fieldItem;

                /**
                 * Gets the value of the fieldItem property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link State.CurrentMappings.FieldItemMap.Destination.FieldItem }
                 *     
                 */
                public State.CurrentMappings.FieldItemMap.Destination.FieldItem getFieldItem() {
                    return fieldItem;
                }

                /**
                 * Sets the value of the fieldItem property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link State.CurrentMappings.FieldItemMap.Destination.FieldItem }
                 *     
                 */
                public void setFieldItem(State.CurrentMappings.FieldItemMap.Destination.FieldItem value) {
                    this.fieldItem = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "order",
                    "caption",
                    "elementName",
                    "fieldType",
                    "isRoot",
                    "parentElementName",
                    "rootElementName"
                })
                public static class FieldItem {

                    @XmlElement(name = "Order")
                    protected byte order;
                    @XmlElement(name = "Caption", required = true)
                    protected String caption;
                    @XmlElement(name = "ElementName", required = true)
                    protected String elementName;
                    @XmlElement(name = "FieldType", required = true)
                    protected String fieldType;
                    @XmlElement(name = "IsRoot", required = true)
                    protected String isRoot;
                    @XmlElement(name = "ParentElementName", required = true)
                    protected String parentElementName;
                    @XmlElement(name = "RootElementName", required = true)
                    protected String rootElementName;

                    /**
                     * Gets the value of the order property.
                     * 
                     */
                    public byte getOrder() {
                        return order;
                    }

                    /**
                     * Sets the value of the order property.
                     * 
                     */
                    public void setOrder(byte value) {
                        this.order = value;
                    }

                    /**
                     * Gets the value of the caption property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCaption() {
                        return caption;
                    }

                    /**
                     * Sets the value of the caption property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCaption(String value) {
                        this.caption = value;
                    }

                    /**
                     * Gets the value of the elementName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getElementName() {
                        return elementName;
                    }

                    /**
                     * Sets the value of the elementName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setElementName(String value) {
                        this.elementName = value;
                    }

                    /**
                     * Gets the value of the fieldType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFieldType() {
                        return fieldType;
                    }

                    /**
                     * Sets the value of the fieldType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFieldType(String value) {
                        this.fieldType = value;
                    }

                    /**
                     * Gets the value of the isRoot property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIsRoot() {
                        return isRoot;
                    }

                    /**
                     * Sets the value of the isRoot property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIsRoot(String value) {
                        this.isRoot = value;
                    }

                    /**
                     * Gets the value of the parentElementName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getParentElementName() {
                        return parentElementName;
                    }

                    /**
                     * Sets the value of the parentElementName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setParentElementName(String value) {
                        this.parentElementName = value;
                    }

                    /**
                     * Gets the value of the rootElementName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRootElementName() {
                        return rootElementName;
                    }

                    /**
                     * Sets the value of the rootElementName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRootElementName(String value) {
                        this.rootElementName = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="FieldItem">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fieldItem"
            })
            public static class Source {

                @XmlElement(name = "FieldItem", required = true)
                protected State.CurrentMappings.FieldItemMap.Source.FieldItem fieldItem;

                /**
                 * Gets the value of the fieldItem property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link State.CurrentMappings.FieldItemMap.Source.FieldItem }
                 *     
                 */
                public State.CurrentMappings.FieldItemMap.Source.FieldItem getFieldItem() {
                    return fieldItem;
                }

                /**
                 * Sets the value of the fieldItem property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link State.CurrentMappings.FieldItemMap.Source.FieldItem }
                 *     
                 */
                public void setFieldItem(State.CurrentMappings.FieldItemMap.Source.FieldItem value) {
                    this.fieldItem = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="FieldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="IsRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ParentElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="RootElementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "order",
                    "caption",
                    "elementName",
                    "fieldType",
                    "isRoot",
                    "parentElementName",
                    "rootElementName"
                })
                public static class FieldItem {

                    @XmlElement(name = "Order")
                    protected byte order;
                    @XmlElement(name = "Caption", required = true)
                    protected String caption;
                    @XmlElement(name = "ElementName", required = true)
                    protected String elementName;
                    @XmlElement(name = "FieldType", required = true)
                    protected String fieldType;
                    @XmlElement(name = "IsRoot", required = true)
                    protected String isRoot;
                    @XmlElement(name = "ParentElementName", required = true)
                    protected String parentElementName;
                    @XmlElement(name = "RootElementName", required = true)
                    protected String rootElementName;

                    /**
                     * Gets the value of the order property.
                     * 
                     */
                    public byte getOrder() {
                        return order;
                    }

                    /**
                     * Sets the value of the order property.
                     * 
                     */
                    public void setOrder(byte value) {
                        this.order = value;
                    }

                    /**
                     * Gets the value of the caption property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCaption() {
                        return caption;
                    }

                    /**
                     * Sets the value of the caption property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCaption(String value) {
                        this.caption = value;
                    }

                    /**
                     * Gets the value of the elementName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getElementName() {
                        return elementName;
                    }

                    /**
                     * Sets the value of the elementName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setElementName(String value) {
                        this.elementName = value;
                    }

                    /**
                     * Gets the value of the fieldType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFieldType() {
                        return fieldType;
                    }

                    /**
                     * Sets the value of the fieldType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFieldType(String value) {
                        this.fieldType = value;
                    }

                    /**
                     * Gets the value of the isRoot property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIsRoot() {
                        return isRoot;
                    }

                    /**
                     * Sets the value of the isRoot property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIsRoot(String value) {
                        this.isRoot = value;
                    }

                    /**
                     * Gets the value of the parentElementName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getParentElementName() {
                        return parentElementName;
                    }

                    /**
                     * Sets the value of the parentElementName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setParentElementName(String value) {
                        this.parentElementName = value;
                    }

                    /**
                     * Gets the value of the rootElementName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRootElementName() {
                        return rootElementName;
                    }

                    /**
                     * Sets the value of the rootElementName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRootElementName(String value) {
                        this.rootElementName = value;
                    }

                }

            }

        }

    }

}
