//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.11 at 02:40:36 PM AST 
//


package com.dovico.importexporttool.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Result.CustomTemplates }
     * 
     */
    public Result.CustomTemplates createResultCustomTemplates() {
        return new Result.CustomTemplates();
    }

    /**
     * Create an instance of {@link Result.CustomTemplates.CustomTemplate }
     * 
     */
    public Result.CustomTemplates.CustomTemplate createResultCustomTemplatesCustomTemplate() {
        return new Result.CustomTemplates.CustomTemplate();
    }

    /**
     * Create an instance of {@link Result.CustomTemplates.CustomTemplate.Values }
     * 
     */
    public Result.CustomTemplates.CustomTemplate.Values createResultCustomTemplatesCustomTemplateValues() {
        return new Result.CustomTemplates.CustomTemplate.Values();
    }

    /**
     * Create an instance of {@link Result.CustomTemplates.CustomTemplate.Values.Value }
     * 
     */
    public Result.CustomTemplates.CustomTemplate.Values.Value createResultCustomTemplatesCustomTemplateValuesValue() {
        return new Result.CustomTemplates.CustomTemplate.Values.Value();
    }

}
